name: tjvanderheeft
favicon: null
layout_spectrum: 0.027630140306428075
typography_spectrum: 0.12237671040929854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.43765878351405263
  lightness: 0.9098328247200698
  saturation: 0.18503321264870465
  rhythmicContrast: 0.3065202571451664
purpose: []
